#!/usr/bin/env node
/**
 * Refreshes _data/dev9b.yml from the F9XR's Dev9b feed.
 *
 * GitHub Pages builds Jekyll without network access, so the homepage's Dev9b
 * section cannot read the remote sitemap at build time. Instead the posts are
 * snapshotted into a data file and rendered statically. Re-run this script when
 * new Dev9b posts land:
 *
 *   node fetch-dev9b.mjs
 *
 * The RSS feed is the source rather than sitemap.xml because it carries titles,
 * dates, and summaries; the sitemap only has URLs and lastmod.
 */
import { writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const OUT = join(here, '..', '_data', 'dev9b.yml');

const FEED = 'https://f9xr.org/dev9b/index.xml';
const SITE = 'https://f9xr.org/dev9b/';
const MAX_SUMMARY = 200;

const ENTITIES = {
  amp: '&',
  lt: '<',
  gt: '>',
  quot: '"',
  apos: "'",
  nbsp: ' ',
  hellip: '…',
  mdash: '—',
  ndash: '–',
  rsquo: '’',
  lsquo: '‘',
  ldquo: '“',
  rdquo: '”'
};

function decodeEntities(str) {
  return str.replace(/&(#x?[0-9a-f]+|[a-z]+);/gi, (match, body) => {
    if (body[0] === '#') {
      const code = body[1] === 'x' || body[1] === 'X'
        ? parseInt(body.slice(2), 16)
        : parseInt(body.slice(1), 10);
      return Number.isFinite(code) ? String.fromCodePoint(code) : match;
    }
    const named = ENTITIES[body.toLowerCase()];
    return named === undefined ? match : named;
  });
}

function stripHtml(str) {
  return str.replace(/<[^>]*>/g, ' ');
}

function tidy(str) {
  // Decode first: the feed's descriptions are HTML-escaped, so tags arrive as
  // &lt;p&gt; and would survive a tag strip that ran before decoding.
  return stripHtml(decodeEntities(str)).replace(/\s+/g, ' ').trim();
}

function truncate(str, max) {
  if (str.length <= max) return str;
  const cut = str.slice(0, max);
  const lastSpace = cut.lastIndexOf(' ');
  return (lastSpace > max * 0.6 ? cut.slice(0, lastSpace) : cut).replace(/[,;:.\s]+$/, '') + '…';
}

function pick(xml, tag) {
  const match = new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`).exec(xml);
  return match ? match[1] : '';
}

function yamlQuote(str) {
  return `"${str.replace(/\\/g, '\\\\').replace(/"/g, '\\"')}"`;
}

function toIsoDate(value) {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) {
    throw new Error(`Unparseable pubDate: ${value}`);
  }
  return date.toISOString().slice(0, 10);
}

function toIsoDuration(xml) {
  const raw = pick(xml, 'duration');
  const match = /^P(?:(\d+)D)?T?(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?$/.exec(raw.trim());
  if (!match) return null;
  const [, d, h, m, s] = match.map((part) => (part === undefined ? 0 : Number(part)));
  const total = d * 86400 + h * 3600 + m * 60 + s;
  const parts = [];
  if (h || d) parts.push(`${h || d * 24}h`);
  if (m) parts.push(`${m}m`);
  if (!parts.length && s) parts.push(`${s}s`);
  return parts.join(' ') || `${total}s`;
}

const response = await fetch(FEED, {
  headers: { 'user-agent': 'f9xr-articles-dev9b-sync (+https://f9xr.org)' }
});
if (!response.ok) {
  console.error(`Fetch failed: ${FEED} responded ${response.status}`);
  process.exit(1);
}

const xml = await response.text();
const items = [...xml.matchAll(/<item>([\s\S]*?)<\/item>/g)].map((m) => m[1]);
if (!items.length) {
  console.error(`No <item> elements found in ${FEED}. Refusing to overwrite the data file.`);
  process.exit(1);
}

const posts = items
  .map((item) => {
    const link = tidy(pick(item, 'link'));
    if (!link.startsWith('http')) return null;
    // Normalise to https and drop the feed's index.html suffix if present.
    const url = link.replace(/^http:/, 'https:').replace(/index\.html$/, '');
    const title = tidy(pick(item, 'title'));
    if (!title || !url.includes('/dev9b/')) return null;
    return {
      title,
      url,
      date: toIsoDate(pick(item, 'pubDate')),
      author: tidy(pick(item, 'author')) || "F9XR Team",
      summary: truncate(tidy(pick(item, 'description')), MAX_SUMMARY),
      duration: toIsoDuration(item)
    };
  })
  .filter(Boolean)
  .sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : a.title.localeCompare(b.title)));

if (!posts.length) {
  console.error('No usable posts parsed. Refusing to overwrite the data file.');
  process.exit(1);
}

const lines = [
  '# Generated by tools/fetch-dev9b.mjs. Do not edit by hand.',
  '# Source: ' + FEED,
  '# Re-run `node tools/fetch-dev9b.mjs` after new posts are published on Dev9b.',
  ''
];
for (const post of posts) {
  lines.push(`- title: ${yamlQuote(post.title)}`);
  lines.push(`  url: ${yamlQuote(post.url)}`);
  lines.push(`  date: ${yamlQuote(post.date)}`);
  lines.push(`  author: ${yamlQuote(post.author)}`);
  if (post.summary) lines.push(`  summary: ${yamlQuote(post.summary)}`);
  if (post.duration) lines.push(`  duration: ${yamlQuote(post.duration)}`);
}

await writeFile(OUT, lines.join('\n') + '\n', 'utf8');
console.log(`_data/dev9b.yml written: ${posts.length} posts (newest ${posts[0].date}).`);
console.log(`Blog index: ${SITE}`);